# Generated by Django 5.1.2 on 2024-10-23 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_brand_active_brand_created_at_brand_updated_at_and_more'),
    ]

    operations = [
    ]
